name: Deploy app in EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ secrets.INSTANCE_REGION_PROD }}

      - name: Realizando Upload app para a EC2
        run: |
          tar -czf - app | aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=InstanceIds,Values=${{ secrets.INSTANCE_ID_PROD }}" \
            --parameters '{"commands":["rm -rf /var/www/html/index.html", "tar -xzf - -C /var/www/html/"]}' \
            --timeout-seconds 600 \
            --max-concurrency "50" \
            --max-errors "0"

      - name: Verificar se tem erros de configuração nginx
        run: |
          sudo nginx -t

      - name: Startando nginx
        run: |
          sudo /etc/init.d/nginx start    

      - name: Recarregando NGINX
        run: sudo nginx -s reload    
